apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardhat
  namespace: default
  labels:
    app: edge_ai
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: edge_ai
  template:
    metadata:
      labels:
        app: edge_ai
    spec:
      runtimeClassName: {{ .Values.runtimeClassName }}
      containers:
        - name: hardhat-detection
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /app/data
              name: data-volume
          ports:
            - containerPort: {{ .Values.service.ports.port5000 }}
            - containerPort: {{ .Values.service.ports.port8080 }}
          resources:
            limits:
              nvidia.com/gpu: 1
      imagePullSecrets:
        - name: azure-acr
      volumes:
        - name: data-volume
          emptyDir: {}
